development:
  adapter: postgresql
  encoding: unicode
  database: sipi_development
  pool: 5
  username: sipi
  password: sipi1

test:
  adapter: postgresql
  encoding: unicode
  database: sipi_test
  pool: 5
  username: sipi
  password: sipi1

production:
  adapter: postgresql
  encoding: unicode
  database: sipi_production
  pool: 5
  username: sipi
  password: sipi1

