development:
  adapter: postgresql
  encoding: UTF-8
  database: sipi_development
  host: localhost
  pool: 5
  username: sipi
  password: sipi1

test:
  adapter: postgresql
  encoding: UTF-8
  database: sipi_test
  host: localhost
  pool: 5
  username: sipi
  password: sipi1
